on: push
name: bad_json
jobs:
  bad_json_validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: bad json
        id: bad_json
        continue-on-error: true
        uses: nats-io/jetstream-gh-action/validate/stream@master
        with:
          config: action/testdata/bad-json.json
      - name: expect_failure
        if: steps.bad_json.outcome != 'failure'
        run: exit 1
      - name: report_failure
        if: steps.bad_json.outcome == 'failure'
        run: echo "bad json file succesfully failed to validate"
