on: push
name: empty_json
jobs:
  empty_json_validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: empty json
        id: empty_json
        continue-on-error: true
        uses: nats-io/jetstream-gh-action/validate/stream@master
        with:
          config: action/testdata/bad-json.json
      - name: expect_failure
        if: steps.empty_json.outcome != 'failure'
        run: exit 1
      - name: report_failure
        if: steps.empty_json.outcome == 'failure'
        run: echo "empty json file succesfully failed to validate"
